### PR TITLE
Python2 to Python3

### PR DESCRIPTION
**Pull request by Shoban94**
Have changed the division operator, print statements and integer type casting. Also have added the future packages to the codes to make it compatible with py2 and py3 in future.

### CODE REVIEW

**Comment by Shoban94** [comment]
I have around three more examples to change, apart from that I have 6 examples for which I don't have the Dcompass, Touch and IR remote sensors to check it with BrickPi

**Comment by karan259** [comment]
@Shoban94 any reason why there is another BrickPi.py in sensor examples folder. Other that that the PR looks good

**Comment by DexterInd** [comment]
Hey @Shoban94 , just wanted to followup on the question @karan259 made up there.

**Comment by Shoban94** [comment]
Hi @John and @karan259 , I have kept a BrickPi.py in the sensor examples folder as I see from the ReadME [here](https://github.com/DexterInd/BrickPi_Python/blob/master/Sensor_Examples/README.md) the sensor examples needs a copy of BrickPi, so I thought it would be better to place one there by default

**Comment by CleoQc** [comment]
@Shoban94  that was valid before we install BrickPi.py system-wide. The file is no longer needed. @karan259  can you confirm?

**Pull request merged**
